### PR TITLE
Fix when t2d trying to remove pip dependencies with non-root user

### LINKED ISSUE #195: Fix when t2d trying to remove pip dependencies with odoo user
When trying to create a container with travisfile2dockerfile using user **odoo** and image **vauxoo/odoo-80-image-shippable-auto**

execute_command

Running the build runs an error when you try to uninstall the dependencies
execute_1
error_uninstall_pip

### PR DESCRIPTION
**Pull request by mapuerta**
This PR resolves fix #195

### CODE REVIEW

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio 

Ready for review

I tried these changes using this [script](https://gist.github.com/mapuerta/dddfec199a7f10639592cd0bd51192bb)
execute_test_script
**Install dependencies**
installing_pip

**Generate the image**
image

**Run entrypoint**
testing_entrypoint

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio 

Ready for review

I tried these changes using this [script](https://gist.github.com/mapuerta/dddfec199a7f10639592cd0bd51192bb)
execute_test_script
**Install dependencies**
installing_pip

**Generate the image**
image

**Run entrypoint**
testing_entrypoint

**Comment by ruiztulio** [comment]
@moylop260 LGTM

**Comment by LuisAlejandro** [comment]
chmodding 777 LGTY?

**Comment by ruiztulio** [comment]
@LuisAlejandro in the scope of the issue yes.

**Comment by LuisAlejandro** [comment]
Well, changing the owner and permissions to such important folders looks a little too much intrusive for my taste. I would suggest using sudo for the operation instead.

Cheers

**Comment by moylop260** [comment]
The idea is remove from sudoers to odoo user (because could install and execute intrusive packages).
What other solution you could fix it without use a virtualenv?

**Comment by LuisAlejandro** [comment]
You could edit `/etc/sudoers` to only allow the use of specific binaries for the `odoo` user. For example:

```
odoo ALL=(ALL) !ALL
odoo ALL=NOPASSWD: /usr/local/bin/pip
```

The first line will restrict the `odoo` user from running any command as sudo. The second line will give the `odoo` user permissions to only run `pip` as sudo. You can add other commands separated with spaces.

**Comment by moylop260** [comment]
The main issue to fix is allow run the following command without permission errors:
`docker run --user=odoo -it --rm vauxoo/odoo-80-image-shippable-auto pip uninstall -y astroid`
```bash
Uninstalling astroid-1.5.0:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/uninstall.py", line 76, in run
    requirement_set.uninstall(auto_confirm=options.yes)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 346, in uninstall
    req.uninstall(auto_confirm=auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/lib/python2.7/shutil.py", line 300, in move
    rmtree(src)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/astroid-1.5.0-py2.7.egg-info/dependency_links.txt'
```

With your proposal the issue is not fixed:

screen shot 2017-02-17 at 11 09 48 am

NOTE: Maybe the best solution is to use a virtualenv 😢

**Comment by ruiztulio** [comment]
@moylop260,


Consider this is not a production image, is a temporary image just for 
development and test purposes that will be destroyed after a certain 
period of time, that's why I'm not concerned that much about being 
permissive, in the other hand giving the user sudo permissions is about 
the same that allow root login.


A better solution would be:

-  Allow sudo with password

-  Generate the password at build time and send it via email (when the 
runbot build is done)

-  Only allow ssh access with keys


But that is more time consuming (perhaps you want to do this in a later 
stage)

**Comment by LuisAlejandro** [comment]
Well, I'm not concerned about security problems because of the fact that
this a development image, I'm concerned with consistency problems (expect
ugly bugs in the future) because apps will expect certain permissions and
owners on these folders.

Just take a little more time thinking this one through ;-)



Luis Alejandro Martínez Faneyth
Blog: http://huntingbears.com.ve
Github: http://github.com/LuisAlejandro
Twitter: http://twitter.com/LuisAlejandro

CODE IS POETRY

2017-02-17 13:14 GMT-04:00 Tulio Ruiz <notifications@github.com>:

File: odoo-shippable/scripts/library.sh [hunk 1]
```diff
@@ -53,6 +53,14 @@ createuser_custom(){
     echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/100-vauxoo-sudoers
     su - ${USER} -c "git config --global user.name ${USER}"
     su - ${USER} -c "git config --global user.email ${USER}@email.com"
+    cat >> /home/${USER}/.bashrc << 'EOF'
+source ${REPO_REQUIREMENTS}/virtualenv/python2.7/bin/activate
```
Comment (moylop260) [inline odoo-shippable/scripts/library.sh]: this `source` should be executed just for `root` and `odoo` users

File: odoo-shippable/scripts/library.sh [hunk 2]
```diff
@@ -53,6 +53,14 @@ createuser_custom(){
...
+source ${REPO_REQUIREMENTS}/virtualenv/nodejs/bin/activate
+EOF
+    cat >> /home/${USER}/.zshrc << 'EOF'
+source ${REPO_REQUIREMENTS}/virtualenv/python2.7/bin/activate
```
Comment (moylop260) [inline odoo-shippable/scripts/library.sh]: Same comment above

**Comment by moylop260** [comment]
FYI I'm checking the travis image and they are using a virtualenv too with `source` to manage python packages:

screen shot 2017-02-20 at 9 56 22 am

We will try it something similar

File: odoo-shippable/scripts/build-image.sh [hunk 3]
```diff
@@ -110,6 +110,11 @@ git_clone_copy "${PYLINT_REPO}" "master" "conf/pylint_vauxoo_light_vim.cfg" "${R
 git_clone_copy "${PYLINT_REPO}" "master" "conf/.jslintrc" "${REPO_REQUIREMENTS}/linit_hook/travis/cfg/.jslintrc"
 ln -sf ${REPO_REQUIREMENTS}/linit_hook/git/* /usr/share/git-core/templates/hooks/
 
+# Creating virtual environments for python and node js
+mkdir -p ${REPO_REQUIREMENTS}/virtualenv/python2.7
```
Comment (moylop260) [inline odoo-shippable/scripts/build-image.sh]: You don't need `mkdir` because `virtualenv` execute a `mkdir` too

File: odoo-shippable/scripts/library.sh [hunk 4]
```diff
@@ -53,6 +53,16 @@ createuser_custom(){
     echo "${USER} ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/100-vauxoo-sudoers
     su - ${USER} -c "git config --global user.name ${USER}"
     su - ${USER} -c "git config --global user.email ${USER}@email.com"
+    if [ ${USER} == "odoo" ] || [ ${USER} == "root" ]; then
```
Comment (moylop260) [inline odoo-shippable/scripts/library.sh]: The user `root` is not created because is created from OS.
What about move this bash change to `build-image.sh` script?

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio. 
Ready for review. This PR related Vauxoo/travis2docker/pull/89

Testing the changes using this [script](https://gist.github.com/mapuerta/dddfec199a7f10639592cd0bd51192bb)

**Installed pip dependencies**
installid_pip
**Installed nodejs dependencies**
installing_nodejs

test_travis

Folders with virtual environments were created
test_ls
ls_nodejs

**Comment by mapuerta** [comment]
@moylop260 @ruiztulio ready for review

**Comment by ruiztulio** [comment]
👍
